default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: smtp.gmail.com
      port: 587
      domain: gmail.com
      authentication: :login
      user_name: YourAccountName@gmail.com
      password: YourGoogleAppPassword
